name:                ded

dependencies:
- base
- directory

ghc-options:
- -Werror
- -Weverything
- -Wno-missing-safe-haskell-mode
- -Wno-safe
- -Wno-implicit-prelude
- -Wno-prepositive-qualified-module
- -Wno-missing-kind-signatures

executables:
  ded-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
